openapi: 3.1.0
info:
  title: Tea Subscription
  description: |-
    Tea Subscription Backend API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: subscriptions
  - name: customer subscriptions
paths:
  /subscriptions:
    get:
      tags:
        - subscriptions
      summary: Get all subscriptions
      description: Get all subscriptions with the option to sort by price
      parameters:
        - in: query
          name: sort_by_price
          schema:
            type: string
            examples: [asc, desc]
          required: false
          description: Sort subscriptions by price, either ascending or descending
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          examples: [1]
                        type:
                          type: string
                          examples: [subscription]
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                              examples: [commodi]
                            price:
                              type: number
                              examples: [83.12]
                            image_url:
                              type: string
                              examples: [https://loremflickr.com/300/300]
                        relationships:
                          type: object
        "422":
          description: Invalid sort_by_price value
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples: [Value of sort_by_price must be 'asc' or 'desc']
                  status:
                    type: integer
                    examples: [422]
  /subscriptions/{id}:
    get:
      tags:
        - subscriptions
      summary: Get detailed subscription info
      description: Get a detailed subscription including associated teas and customer subscriptions
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The subscription id
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        examples: [1]
                      type:
                        type: string
                        examples: [subscription]
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                            examples: [commodi]
                          price:
                            type: number
                            examples: [83.12]
                          image_url:
                            type: string
                            examples: [https://loremflickr.com/300/300]
                          customer_subscriptions:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                      examples: [1]
                                    type:
                                      type: string
                                      examples: [customer_subscription]
                                    attributes:
                                      type: object
                                      properties:
                                        status:
                                          type: string
                                          examples: [active, inactive]
                                        customer:
                                          type: object
                                          properties:
                                            data:
                                              type: object
                                              properties:
                                                id:
                                                  type: string
                                                  examples: [1]
                                                type:
                                                  type: string
                                                  examples: [customer]
                                                attributes:
                                                  type: object
                                                  properties:
                                                    first_name:
                                                      type: string
                                                      examples: [Kaley]
                                                    last_name:
                                                      type: string
                                                      examples: [Hand]
                                                    email:
                                                      type: string
                                                      examples:
                                                        [
                                                          melina@terry-stamm.example,
                                                        ]
                                                    address:
                                                      type: string
                                                      examples:
                                                        [
                                                          33343 Solomon Ridge,
                                                          Hyattchester,
                                                          CO 36994-5015,
                                                        ]
                      relationships:
                        type: object
                        properties:
                          teas:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                      examples: [1]
                                    type:
                                      type: string
                                      examples: [tea]
                  included:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          examples: [1]
                        type:
                          type: string
                          examples: [tea]
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                              examples: [Dianhong]
                            description:
                              type: string
                              examples:
                                [
                                  Et sequi blanditiis. Et ut sed. Magni consectetur vel.,
                                ]
                            brew_time:
                              type: integer
                              examples: [5]
                            image_url:
                              type: string
                              examples: [https://loremflickr.com/300/300]
        "404":
          description: Invalid subscription id
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples: [Couldn't find Subscription with 'id'=-1]
                  status:
                    type: integer
                    examples: [404]
  /customer_subscriptions/{id}/:
    patch:
      tags:
        - customer subscriptions
      summary: Activate or cancel a customer subscription
      description: Activate or cancel a customer subscription
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The customer subscription id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: string
                  examples: [true, false]
        required: true
      responses:
        "200":
          description: Successful save
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        examples: [1]
                      type:
                        type: string
                        examples: [customer_subscription]
                      attributes:
                        type: object
                        properties:
                          status:
                            type: string
                            examples: [active, inactive]
        "404":
          description: Invalid customer subscription id
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples: [Couldn't find CustomerSubscription with 'id'=-1]
                  status:
                    type: integer
                    examples: [404]
        "422":
          description: Invalid or missing active value
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples:
                      [
                        Value of active must be 'true' or 'false',
                        "param is missing or the value is empty: active",
                      ]
                  status:
                    type: integer
                    examples: [422]
